export const newsData = {
  title:
    "NEET Application Form 2025 (OUT): Registration Link, Last Date to Apply at neet.nta.nic.in",
  editor: "Karan Sapra",
  date: "25 February 2025",
  registration_link: "https://neet.nta.nic.in",
  status: "OUT",
  exam: "NEET 2025",
  event: {
    eventName: "Neet Counselling 2025",
    status: false,
  },
  categories: ["Education", "Exams", "Medical Entrance", "NEET"],
  heading:
    "The NTA has released the NEET application form 2025. The NEET application form date is February 7, 2025, Students can fill the NEET 2025 application form at the official website, neet.nta.nic.in. The NEET application form last date is March 7, 2025. Candidates need to complete their NEET registration 2025 first before filling out the online application form.  Only such candidates who fulfil the eligibility criteria can fill NEET UG application form. ",
  storyData: [
    "NEET 2025 application form date",
    "Eligibility criteria for NEET application form 2025",
    "How to fill NEET UG 2025 application form?",
    "NEET 2025 application form - Specification of scanned documents",
    "NEET application form 2025 documents required",
    " NEET application form 2025 pdf download",
    "NEET application form - Image correction",
    "NEET form 2025 correction window",
    "NEET applicant statistics over the years",
  ],
  importantLinks: [
    { News: "NEET 2025 Application Form OUT; Direct Link to Apply" },
    { Biology: "NEET 2025: Biology: Mind Maps & Important Diagrams" },
    {
      Syllabus:
        "NEET 2025: Syllabus | Most Scoring concepts | NEET PYQ's (2015-24)",
    },
    { PYQs: "NEET PYQ's & Solutions: Physics | Chemistry | Biology" },
  ],
  neetSchedule: {
    "2025-02-07": "NEET 2025 Application Form Start",
    "2025-03-07": "NEET 2025 Form Submission Last Date",
    "2025-04-10": "NEET 2025 Admit Card Release",
    "2025-05-04": "NEET 2025 Exam Date",
    "2025-06-15": "NEET 2025 Result Declaration",
    "2025-07-01": "NEET 2025 Counseling Start",
  },
  eligibilityCriteria: {
    "Minimum Age":
      "Candidate must be at least 17 years old as of December 31, 2025.",
    "Maximum Age": "No upper age limit for NEET 2025.",
    "Educational Qualification":
      "Candidate must have passed 10+2 or equivalent with Physics, Chemistry, Biology/Biotechnology, and English as core subjects.",
    "Minimum Marks (General)":
      "50% aggregate in PCB (Physics, Chemistry, Biology).",
    "Minimum Marks (OBC/SC/ST)": "40% aggregate in PCB.",
    "Minimum Marks (PwD)": "45% aggregate in PCB.",
    "Number of Attempts": "No attempt limit.",
    Nationality:
      "Indian Nationals, NRIs, OCIs, PIOs, and Foreign Nationals are eligible.",
  },
  stepsData: [
    "Registration",
    "Filling Application Form",
    "Uploading the images",
    "Online application fee payment",
    "Printout Of Confirmation Page",
  ],
  neetDetails: [
    "Candidate's Full Name",
    "Father's Name",
    "Mother's Name",
    "Date of Birth",
    "Gender",
    "Category (General/OBC/SC/ST/EWS)",
    "Nationality",
    "Aadhaar Number or Other ID Proof",
    "Mobile Number",
    "Email ID",
    "Permanent Address",
    "Correspondence Address",
    "State of Domicile",
    "Medium of Examination (English/Hindi/Other)",
    "Choice of Exam City (3 Preferences)",
    "Class 10th Details (Board, Year of Passing, Marks)",
    "Class 12th Details (Board, Year of Passing, Marks)",
    "School Name and Address",
    "Subjects Studied in 12th (Physics, Chemistry, Biology, etc.)",
    "Marks Obtained in Each Subject",
    "Total Marks & Percentage in 12th",
    "PwD Status (If Applicable)",
    "Identification Marks (Optional)",
    "Mode of Payment for Application Fee",
    "Scanned Photograph Upload",
    "Scanned Signature Upload",
    "Category Certificate (If Applicable)",
    "PwD Certificate (If Applicable)",
    "Self-Declaration Form (If Applicable for NRI/Foreign Candidates)",
  ],
};
